### ISSUE TITLE
prediction corrected VPC with time-after-dose

### ISSUE THREAD

**Issue by namtien0312** [ggPMXdevelopment/ggPMX#208]
Dear @ggPMXdevelopment team and Dr. @mattfidler,

First of all, thanks for the useful ggplot2-based packages for model diagnostic and data exploration.

I had a concern about how to perform `prediction corrected VPC` with `ggPMX` packages and also how to use `TAD` rather than `TIME`. I have tried to find it in the tutorial, but I can't.

Thank very much,
Tien.

**Comment by baltcir1** [comment]
Dear @namtien0312,
the pcVPC is not yet implemented in ggPMX, but it is planned for this year. Here is an example of code of how to use TAD in any of the graphs (NPDE plot in the example below):
npde_tad = ctr %>% pmx_plot_npde_time(aess = list(x = "TAD"), 
                           labels = list(x = "Time since LAST dose (hours)"))
Best regards,
Irina

**Comment by namtien0312** [comment]
First of all, thank Irina for your help! 

But unfortunately, I had a problem when performing the VPC. Could you please answer for me on this issue for convenience? Here is the code (that comes from your tutorial).

Thank you so much, Tien.

```
one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

fit <- nlmixr(one.cmt, theo_sd, est="saem", control=list(print=0))

pmx_nlmixr(fit) %>% pmx_plot_vpc()
```
![image](https://user-images.githubusercontent.com/68368676/163510428-26cef3de-4aa6-46e2-941a-ae406e786dd7.png)

And, the warming message exist:
```
Warning message:
In grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
```

**Comment by mattfidler** [comment]
The warning message comes from the latest version of R running in windows, though I am unsure why it is happening.  

I would pick the vpc bins to fix this vpc. Something like

```r
     ctr %>% 
       pmx_plot_vpc(bin= pmx_vpc_bin(
          style = "fixed",
          fixedBreaks=c(-10,2, 5, 10,15,50))
       )
```

**Comment by namtien0312** [comment]
Thank Dr. @mattfidler, this problem was solved as your suggestion.

I had an additional error with my dataset although this task worked with the `vpc` function. I prepare an example that illustrates it. 

I appreciate your time to consider me. If needed, I can create a new issue for this bug.

Thank you so much again. 
Best regards, Tien.

```
# Data' purpose illustrates the error and my data set
df = tibble(
  ID = c(rep(1, 6), rep(2, 6)),
  TIME = c(0.00, 12.11, 18.41, 23.89, 36.00, 43.51, 0.00, 12.00, 20.00, 24.00, 36.80, 45.00),
  AMT = c(1000, 1000, NA, 1000, 1000, NA, 1000, 2000, NA, 1000, 1000, NA),
  DUR = c(2.5, 2.5, NA, 2.5, 2.5, NA, 2.5, 2.5, NA, 2.5, 2.5, NA),
  DV = c(NA, NA, 3.0, NA, NA, 9.6, NA, NA, 7.0, NA, NA, 2.8),
  WT = c(rep(55, 6), rep(48, 6))
) %>% 
  mutate(EVID = ifelse(is.na(DV), 1, 0))

model = function() {     
  ini({
    tvCl <- c(0, 4, Inf)
    tvVc <- c(0, 48, Inf)
    
    eta.Vc ~ 0.62
    prop.sd <- 0.051529     
           
  })
  model({
    Cl <- tvCl
    Vc <- tvVc*(WT/70)*exp(eta.Vc)
    
    # dynamical system
    linCmt() ~ prop(prop.sd) 
  })
}

fit = nlmixr(model, df, list(print=0), est="posthoc")

# Output with vpc() as figure below
p1 = vpc(fit, pred_corr = TRUE, show = list(obs_dv = T))
```
Output with `vpc()` function
![image](https://user-images.githubusercontent.com/68368676/163517159-ab5f1ffe-c4c3-4e50-8383-4835df044cd5.png)


Error message with `vpc` in `ggPMX`:
```
p = pmx_nlmixr(fit) %>% pmx_plot_vpc()
#add npde
#Compiling NPDE model...done 
#done
#Compiling VPC model...done
#done (0.57 sec)
#Error in data.frame(PARAM = row.names(pars), VALUE = pars$Estimate, SE = pars$SE,  : 
#arguments imply differing number of rows: 3, 0
```
```
p
#Error: object 'p' not found
```

**Comment by tynsci** [comment]
- Not reproducible in current development version, closing, see #209

**Comment by mattfidler** [comment]
There is no predicted corrected VPC here (which is reproducible).  The VPC is still not doing the right thing.
